export const products= [
    {
        mainImg: "/public/img/1.webp",
        hoverImg: "/public/img/1b.webp",
        brand: "Levi's",
        description: "RELAXED FIT TEE UNISEX",
        discount:0,
        priceNow: ["€ ",0],
        priceOld: "69,99€ ",
    },
    {
        mainImg: "/public/img/2.webp",
        hoverImg: "/public/img/2b.webp",
        brand: "Zara",
        description: "SLIM FIT",
        discount:0,
        priceNow: ["€ ",0],
        priceOld: "19,99€ ",
    },
    {
        mainImg: "/public/img/3.webp",
        hoverImg: "/public/img/3b.webp",
        brand: "Dolce & Gabbana",
        description: "NORMAL FIT",
        discount:0,
        priceNow: ["€ ",0],
        priceOld: "22,99€ ",
    },
    {
        mainImg: "/public/img/4.webp",
        hoverImg: "/public/img/4b.webp",
        brand: "Hugo Boss",
        description: "NORMAL FIT",
        discount:0,
        priceNow: ["€ ",0],
        priceOld: "19,99€ ",
    },
    {
        mainImg: "/public/img/5.webp",
        hoverImg: "/public/img/5b.webp",
        brand: "OVS",
        description: "RELAXED FIT TEE UNISEX",
        discount:0,
        priceNow: ["€ ",0],
        priceOld: "59,99€ ",
    },
    {
        mainImg: "/public/img/6.webp",
        hoverImg: "/public/img/6b.webp",
        brand: "Primark",
        description: "SLIM FIT",
        discount:0,
        priceNow: ["€ ",0],
        priceOld: "22,99€ ",
    },
]